version: '3.5'

services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: config/docker/app.dockerfile
      args:
        PHP_VERSION: 7.3
        DOCKER_ENABLE_BASH: 'on'
        DOCKER_PHP_ENABLE_APCU: 'off'
        DOCKER_PHP_ENABLE_MYSQL: 'on'
        DOCKER_PHP_ENABLE_REDIS: 'on'
        DOCKER_PHP_ENABLE_COMPOSER: 'on'
        DOCKER_PHP_ENABLE_XDEBUG: 'off'
        DOCKER_PHP_ENABLE_LDAP: 'off'
        DOCKER_PHP_ENABLE_MEMCACHED: 'off'
        DOCKER_PHP_ENABLE_MONGODB: 'off'
        DOCKER_PHP_ENABLE_POSTGRESQL: 'off'
        DOCKER_PHP_ENABLE_SYMFONY: 'off'
        DOCKER_USER_UID: 1000
        DOCKER_USER_GID: 1000
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      PHP_IDE_CONFIG: "serverName=Test"
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/conf.d/php-cli.ini
      - ./src/:/var/www
    expose:
      - 9001
    networks:
      - app_network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./src/:/var/www
    networks:
      - app_network

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql/
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    networks:
      - app_network

  # php-worker to run horizon
  php-worker:
    build:
      context: .
      dockerfile: config/docker/worker.dockerfile
      args:
        PHP_VERSION: 7.3
        DOCKER_USER_UID: 1000
        DOCKER_USER_GID: 1000
        DOCKER_INSTALL_REDIS: 'on'
        DOCKER_INSTALL_MYSQL_CLIENT: 'on'
        DOCKER_INSTALL_TAINT: 'on'
        DOCKER_INSTALL_PGSQL: 'off'
        DOCKER_INSTALL_BCMATH: 'off'
        DOCKER_INSTALL_SOAP: 'off'
        DOCKER_INSTALL_ZIP_ARCHIVE: 'off'
        DOCKER_INSTALL_GHOSTSCRIPT: 'off'
        DOCKER_INSTALL_FFMPEG: 'off'
        DOCKER_INSTALL_GMP: 'off'
    volumes:
      - ./src/:/var/www
      - ./config/php-worker/supervisord.conf:/etc/supervisord.conf
      - ./config/php-worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - redis
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./config/phpmyadmin/sessions_ex.ini:/usr/local/etc/php/conf.d/sessions_ex.ini
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - "8080:80"
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local